name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Pack 
      run: dotnet pack --configuration Release
    - name: Publish NuGet 
      run: 
        dotnet nuget push .\Acto-R\bin\Debug\Acto-R.${{secrets.NUGET_VERSION}}.nupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --force-english-output
    - name: Publish NuGet-SourceLink 
      run: 
        dotnet nuget push .\Acto-R\bin\Debug\Acto-R.${{secrets.NUGET_VERSION}}.snupkg --api-key ${{secrets.NUGET_API_KEY}} --source https://api.nuget.org/v3/index.json --force-english-output

